[project]
dependencies = [
  "pandera[mypy]>=0.23.1",
  "fakerator",
]
description = "examples projects for fakerator"
name = "examples"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"

[tool.uv.sources]
fakerator = {path = "../"}

[dependency-groups]
dev = [
  "pytest>=8.3.5",
]
