name: release and deploy

on:
  pull_request:
    branches:
      - main
    types:
      - closed

concurrency:
  group: ${{ github.workflow }}--${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-please:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    permissions:
      id-token: write
      pull-requests: write
      contents: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      release_name: "v${{ steps.release.outputs.major }}-${{ steps.release.outputs.minor }}-${{ steps.release.outputs.patch }}"
      sha: ${{ steps.release.outputs.sha }}
    steps:
      - name: Generate token for release-please
        id: gh_pr_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.THIS_GITHUB_APP_ID }}
          private_key: ${{ secrets.THIS_GITHUB_APP_PRIVATE_KEY }}
          permissions: >-
            {"issues": "write", "pull_requests": "write", "contents": "write"}
          repositories: >-
            ["${{ github.event.repository.name }}"]

      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        id: release
        with:
          token: ${{ steps.gh_pr_token.outputs.token }}
          config-file: .github/release-please/config.json
          manifest-file: .github/release-please/.manifest.json
          target-branch: main

  release-main:
    needs: release-please
    if: needs.release-please.outputs.release_created && github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    permissions:
      id-token: write
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
        with:
          workspaces: |
            fakerator-core -> fakerator-core-target

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: "Publish Package"
        run: |
          uv build
          uv publish --project pyfakerator
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_PASSWORD }}
