name: Rust Tests

on:
  workflow_call:

jobs:
  test:
    name: Test Suite (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    defaults:
      run:
        working-directory: ./fauxgen-core
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
        with:
          workspaces: |
            fauxgen-core -> fauxgen-core-target-${{ matrix.os }}
          key: rust-test-${{ matrix.os }}

      - name: Run check
        run: cargo check --all-targets --all-features

      - name: Run tests
        run: cargo test --all-features

  lints:
    name: Lints
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fauxgen-core
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
        with:
          workspaces: |
            fauxgen-core -> fauxgen-core-target
          key: rust-lint

      - name: Run fmt
        run: cargo fmt --all --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
